### ISSUE TITLE
リポジトリの移管作業

### ISSUE THREAD

**Issue by colorbox** [esminc/bento#138]
### 概要
colorbox/bento -> esminc/bento へとリポジトリを transfer したい。

### TODO

移管時に連携サービスが問題起こさないか調査

 - [x] Heroku
 - [x] Errbit
 - [ ] deppbot

**Comment by colorbox** [comment]
Herokuはアプリが動作する場所であってリポジトリの場所とは関係ないやろ、ということでcheck

**Comment by colorbox** [comment]
Errbitも同様に問題な下げなのでcheck

**Comment by colorbox** [comment]
deppbotはちょっと確証が取れん。
移管後のorganization内のリポジトリもdeppbotのメニューから見えるため、移管後はそのorganizationのメンバならいじれるであろうという認識だが、リポジトリによってdeppbotのメニューから見えたり見えなかったりする。

FAQ見る限り、Organizationに紐付いたリポジトリも見えないとは書いてない。
https://www.deppbot.com/faq

多分大丈夫そうだけどなんか合ったら怖い程度の認識。

ダミーのrailsプロジェクトを立てて、移管作業してどうなるか見てみよう。

**Comment by colorbox** [comment]
試しにどうでも良いrailsプロジェクトをdeppbotに登録した上で移管してみたが、deppbot上から表示が消えた。
検索に引っかからないので、すぐには再設定できないようだ。
再設定を確認したら移管を行う。

**Comment by colorbox** [comment]
移管した上でteamの権限など適切に設定したはずなんだけど[deppbot](https://www.deppbot.com/)から設定メニューが出てこない。
一日ほど待って出てこないかを見てみる。

**Comment by colorbox** [comment]
deppbotの連携がうまくいかないのでもうちょっと検証する。
移管先のorganizationの権限持ってるほかの人に聞いてみる。

**Comment by yucao24hours** [comment]
問い合わせしてみたほうが早いかも？

**Comment by colorbox** [comment]
もう一回検証した上で問い合わせてみます。

**Comment by yucao24hours** [comment]
transfer 済みとの認識ですが、こちらの issue の "DONE の定義" はなんだったでしょうか？
既にそれを満たしているか、もしなにかまだ残っていればそれらを書いておいてもらえると助かります✋

**Comment by colorbox** [comment]
移管作業自体は完了したのでcloseします。
移管先orgに属しているリポジトリがdeppbotから見えないという問題があったため、その旨をdeppbotのサポートに問い合わせていましたが、一向に返答がありませんでした。
deppbotの問題はサポートからの返答があり次第どうにかすることとして、一旦移管を行ってしまいます。

残作業として明記しておくべきものは

 - deppbot関連の作業

となります。

**Comment by yucao24hours** [comment]
わたしが "DONE の定義" といったのは、これのことです👇
https://www.slideshare.net/mobile/Ryuzee/doneexpo-scrumdo

上記を踏まえて「deppbot関連の作業」という書き方をみると、「結局どうしたいんだっけ？」がわからない（のでそのための具体的な手を打てない）ので、それを書いてもらいたかったのでした。

やり残したことがまだある状態でこの issue を close するのであれば、その「やり残したこと」についての issue を新たに作っておいてもらえると助かります。せっかくここに書いてもらっても、 close したら見られることはなくなってしまうので...。

**Comment by colorbox** [comment]
deppbot関連について別issueに書き起こします。 🙏
