### ISSUE TITLE
休日に bento にアクセスするとアプリケーションエラーになる

### ISSUE THREAD

**Issue by yucao24hours** [esminc/bento#151]
## 現象

https://idobata.io/ja/archives/organization/esm/room/bento-user/2017-06-03#message_22307307

休日、すなわち Order レコードとして存在しない日に bento のトップ画面にアクセスしようとすると、アプリケーションエラーでおちる。

## 原因

トップ画面で `@today_order` の存在確認をする条件が適切でないため。

## 方針

休日、すなわち Order レコードとして存在しない日には、トップ画面には注文の成立・非成立情報を出さないようにする。

分担的には `@today_order` をサーバ側で取得するのではなく、画面側で `Order` からひいてくるようにしたほうがいいかもしれない。

## TODO

- [x] バグの修正
- [x] テスト追加
- [x] リファクタ

**Comment by yucao24hours** [comment]
@colorbox （なのかな？このチェックボックスを追加してくれた人へ）
ここでいう
>リファクタ

って、なんのことを指してましたか？
tkm_kj がやってくれた https://github.com/esminc/bento/pull/152/commits/f9bd173d25ad67cf1340c117889533ce3445fca9 の内容のことであれば、既に対応済みなのでここもチェックしてこの issue を close したいきもちです（後からバグは出ましたが、ここでやりたかったことは `リファクタ` までなので、それを管理したい）。

**Comment by colorbox** [comment]
リファクタは完了したという認識なので、このissueはcloseしてしまいます 🙏
