### ISSUE TITLE
発注前にトップページにアクセスすると発注非成立の旨が表示される

### ISSUE THREAD

**Issue by colorbox** [esminc/bento#153]
注文締切前にトップページにアクセスすると、締め切り前にもかかわらず発注非成立のメッセージが表示されてしまう。
事実と異なる表記なので修正したい。
注文締切前は、発注に関するメセージを出さないようにする。

**Comment by yucao24hours** [comment]
厳密には、「締め切り前に __非__ 成立のメッセージが出てしまうので、あたかも __未__ 成立のように見えてしまう」ということですね。（「__未__ 成立のメッセージって今の実装だと出していないはずなんだけどな？」と一瞬なんのことかわからなくてちょっとだけ困ったので...。的確に伝えられるようになると、よりスムーズに意思疎通できると思うので、細かいところですが気をつけてみてください 🙋 ）

**Comment by colorbox** [comment]
微妙な違いで混乱させてしまったようで申し訳ないです。 🙇 
スクショなども添付すれば分かりやすかったでしょうか。
以後気をつけます。 🙏

**Comment by yucao24hours** [comment]
#154 で対応済み
