### ISSUE TITLE
deppbotの再導入

### ISSUE THREAD

**Issue by colorbox** [esminc/bento#155]
### 概要
リポジトリの移管以前は、[deppbot](https://www.deppbot.com/)を使用していた。

しかし、リポジトリの移管以降、deppbotの管理画面から,bentoのリポジトリを参照することができなくなった。
このため、現在はdeppbotが正常に動作していないと思われる。
これをどうにかして復帰させたい。

### 完了条件
 - [ ] deppbotが`bundle update`実行のPRを新たに出すことを確認する

**Comment by yucao24hours** [comment]
内容がわかりやすくてとてもいいと思いました！🙏

**Comment by colorbox** [comment]
導入 completed
